name: moelholm.com
title: moelholm.com
url: https://moelholm.com
description: Blog by Nicky Bass Moelholm
google_analytics: UA-7400692-1
markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false  
    block:
      line_numbers: true
collections_dir: blog_collections
collections:
  running:
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title
    tags: true
  software_engineering:
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title
    tags: true
  toots:
    output: false
  activities:
    output: false
feed:
  collections:
    - running
    - software_engineering
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Feature toggles
features:
  show_software_engineering: false

# GitHub Discussions (giscus) configuration
giscus:
  repo_name: "moelholm/moelholm.github.io"
  repo_id: "MDEwOlJlcG9zaXRvcnkxOTU1MzQ0MTk="
  category_name: "Announcements"
  category_id: "DIC_kwDOC6eeU84C0DZR"